name: Human Aware Rllib

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build_osx:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Include $CONDA in $PATH
      run: |
        echo ::add-path::$CONDA/condabin
        sudo chown -R runner $CONDA
    - name: Install dependencies
      run: |
        conda create -n harl python=3.7
        conda activate harl
        python -m pip install --upgrade pip
        ./install.sh
        pip install tensorflow==2.1.0
    - name: Test with unittest
      run: |
        conda activate harl
        ./run_tests.sh
    
